version: "3"
# Need to make my own changes
services:
  webui:
    build: webui
    image: 127.0.0.1:30000/webui:v0.1
    ports:
    - "8000:80"

  redis:
    image: redis

  worker:
    build: worker
    image: 127.0.0.1:30000/worker:v0.1
    deploy:
      replicas: 10
